### ISSUE TITLE
Python SDK make Error

### ISSUE THREAD

**Issue by Michael-Yan-wun** [TW-NCHC/TWCC-CLI#57]
**Describe the bug**
I download the whole package of TWCC-CLI, and there is an error when I run the following code.
I expect to implement python function to control TWCC-CLI without command line.

**Version Info**
TWCC-CLI version : 0.6.0
OS: ubuntu 18.04
Python version: 3.8.5

``` code

import os,sys
TWCC_PATH = '/home/aiwin_dev/tmp/TWCC-CLI'
sys.path[0]=TWCC_PATH

import time
from twccli.twcc.services.solutions import solutions
from twccli.twcc.services.base import acls, users, image_commit, projects, Flavors, iservice
from twccli.twcc.session import session_start, Session2
from twccli.twcc.services.compute import GpuSite as Sites

twcc_site = Sites(debug=False).getSolList(reverse=True)

```

The error traceback:
```code
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/click/globals.py",line 23, in get current context
return getattr( local,'stack") [-11 AttributeError:_thread._local' object has no attribute 'stack'During handling of the above exception, another exception occurred:Traceback (most recent call last):
File "client.py", line 13, in <module>
twcc_site = Sites (debug=False) .getSolList (reverse=True)
File "/home/aiwin dev/tmo/TWCC-CLI/twccli/twcc/services/compute.py", line 41, in init GouService. init (self)
File "/home/aiwin_dev/tmp/TWCC-CLI/twccli/twcc/services/generic.py", line 187, in .init GenericService. init (self)
File "/home/aiwin dev/tmp/TWCC-CLI/twccli/twcc/services/generic.py", line 23, in ._init self._debug_ = isDebug()
File "/usr/lib/python3/dist-packages/click/decorators.py", line 55, in new func ctx = aet current context ()
File "/usr/lib/ovthon3/dist-packages/click/alobals.ov"
line 26, in get _current_context
raise RuntimeError( 'There is no active click context.")
RuntimeError: There is no active click context.
```

Please help me figure out this error.

**Comment by AugustChaoTW** [comment]
hi, @Michael-Yan-wun 

The problem happens when loading `util.py` but no proper pass environment variables to this library. We will release fix in next release.

A quick fix is change following code in https://github.com/twcc/TWCC-CLI/blob/master/twccli/twcc/util.py#L48

from 
```python
@pass_environment
def isDebug(env):
    return True if os.environ.get(
        "TWCC_CLI_STAGE") == "dev" or env.verbose else False
```

to 
```python
def isDebug():
    return False
```

then your cli behavior will be correct!
